application: devfestpraha
version: pardubice
# NOTE: URL is CHANGEME.dart-lang.appspot.com
#       To get your own staging server, change 'CHANGEME' to something
#       like 'kathyw' or 'kathyw-dartium'.
#
#       To deploy to dartlang.org (only from a clean master workspace)
#       change CHANGEME to a date string: YYYY-MM-DD.
#       For more information on making changes, see goto/dartsiteupdate.
#
# IMPORTANT: AFTER changing the version, DO THIS:
#       make clean
#       make build

runtime: python27
api_version: 1
threadsafe: true

#default_expiration: "1d"

handlers:
- url: /.*
  script: redirect.app